http:
  routers:
    websocket-reverb:
      rule: "Host(`admin-payment.whusnet.com`) && PathPrefix(`/app/`)"
      entryPoints:
        - https
      service: websocket-reverb-service
      tls:
        certResolver: letsencrypt
      priority: 200

  services:
    websocket-reverb-service:
      loadBalancer:
        servers:
          - url: "http://reverb:8081"
        passHostHeader: true
        serversTransport: websocket-transport

  serversTransports:
    websocket-transport:
      disableHTTP2: true
      forwardingTimeouts:
        dialTimeout: 30s
        responseHeaderTimeout: 0s
        idleConnTimeout: 0s
